// <auto-generated />
using MamazonApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MamazonApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250212132143_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MamazonApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("ActiveUser")
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Cep")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumberHouse")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ActiveUser = 1,
                            Adress = "Rua do Xesque",
                            Cep = 11760000,
                            City = "Itariri",
                            Complement = "Casa",
                            Email = "alessandro-s-nascimento@hotmail.com",
                            Neighborhood = "Paraguai 1",
                            NumberHouse = 69,
                            Password = "123456",
                            State = "SP",
                            UserName = "Alessandro Santos do Nascimento"
                        },
                        new
                        {
                            UserId = 2,
                            ActiveUser = 1,
                            Adress = "Rua do Suco",
                            Cep = 11760000,
                            City = "Itariri",
                            Complement = "Casa",
                            Email = "guilherme-m-pinho@hotmail.com",
                            Neighborhood = "Pop",
                            NumberHouse = 8000,
                            Password = "456789",
                            State = "SP",
                            UserName = "Guilherme Ferreira de Morais Pinho"
                        },
                        new
                        {
                            UserId = 3,
                            ActiveUser = 0,
                            Adress = "Rua do Fé",
                            Cep = 11760000,
                            City = "Itariri",
                            Complement = "Casa",
                            Email = "vinicius-s-duarte@hotmail.com",
                            Neighborhood = "Paraguai 2",
                            NumberHouse = 24,
                            Password = "987654",
                            State = "SP",
                            UserName = "Vinicius Souza Duarte"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
