// <auto-generated />
using MamazonApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MamazonApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250214163425_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MamazonApi.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("Citys");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Itariri",
                            StateId = 1
                        });
                });

            modelBuilder.Entity("MamazonApi.Models.Email", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailId"));

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EmailId");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            EmailId = 1,
                            UserEmail = "alessandro-s-nascimento@hotmail.com"
                        },
                        new
                        {
                            EmailId = 2,
                            UserEmail = "guilherme-m-pinho@hotmail.com"
                        },
                        new
                        {
                            EmailId = 3,
                            UserEmail = "vinicius-s-duarte@hotmail.com"
                        });
                });

            modelBuilder.Entity("MamazonApi.Models.Password", b =>
                {
                    b.Property<int>("PasswordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PasswordId"));

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PasswordId");

                    b.ToTable("Passwords");

                    b.HasData(
                        new
                        {
                            PasswordId = 1,
                            UserPassword = "123456"
                        },
                        new
                        {
                            PasswordId = 2,
                            UserPassword = "456789"
                        },
                        new
                        {
                            PasswordId = 3,
                            UserPassword = "987654"
                        });
                });

            modelBuilder.Entity("MamazonApi.Models.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidenceId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Cep")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumberHouse")
                        .HasColumnType("int");

                    b.HasKey("ResidenceId");

                    b.HasIndex("CityId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 1,
                            Adress = "Rua da escuridão",
                            Cep = 11760000,
                            CityId = 1,
                            Complement = "Casa",
                            Neighborhood = "Paraguai 1",
                            NumberHouse = 69
                        },
                        new
                        {
                            ResidenceId = 2,
                            Adress = "Rua do suco",
                            Cep = 11760000,
                            CityId = 1,
                            Complement = "Casa",
                            Neighborhood = "Pop",
                            NumberHouse = 8000
                        },
                        new
                        {
                            ResidenceId = 3,
                            Adress = "Sua da fé",
                            Cep = 11760000,
                            CityId = 1,
                            Complement = "Casa",
                            Neighborhood = "Paraguai 1",
                            NumberHouse = 24
                        });
                });

            modelBuilder.Entity("MamazonApi.Models.ResidencesUser", b =>
                {
                    b.Property<int>("ResidencesUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResidencesUserId"));

                    b.Property<int>("ResidenceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ResidencesUserId");

                    b.HasIndex("ResidenceId");

                    b.HasIndex("UserId");

                    b.ToTable("ResidencesUsers");

                    b.HasData(
                        new
                        {
                            ResidencesUserId = 1,
                            ResidenceId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ResidencesUserId = 2,
                            ResidenceId = 2,
                            UserId = 2
                        },
                        new
                        {
                            ResidencesUserId = 3,
                            ResidenceId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MamazonApi.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            StateName = "SP"
                        });
                });

            modelBuilder.Entity("MamazonApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("ActiveUser")
                        .HasColumnType("int");

                    b.Property<int>("EmailId")
                        .HasColumnType("int");

                    b.Property<int>("PasswordId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.HasIndex("EmailId");

                    b.HasIndex("PasswordId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ActiveUser = 1,
                            EmailId = 1,
                            PasswordId = 1,
                            UserName = "Alessandro Santos do Nascimento"
                        },
                        new
                        {
                            UserId = 2,
                            ActiveUser = 1,
                            EmailId = 2,
                            PasswordId = 2,
                            UserName = "Guilherme Ferreira de Morais Pinho"
                        },
                        new
                        {
                            UserId = 3,
                            ActiveUser = 0,
                            EmailId = 3,
                            PasswordId = 3,
                            UserName = "Vinicius Souza Duarte"
                        });
                });

            modelBuilder.Entity("MamazonApi.Models.City", b =>
                {
                    b.HasOne("MamazonApi.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("MamazonApi.Models.Residence", b =>
                {
                    b.HasOne("MamazonApi.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MamazonApi.Models.ResidencesUser", b =>
                {
                    b.HasOne("MamazonApi.Models.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MamazonApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MamazonApi.Models.User", b =>
                {
                    b.HasOne("MamazonApi.Models.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MamazonApi.Models.Password", "Password")
                        .WithMany()
                        .HasForeignKey("PasswordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Password");
                });
#pragma warning restore 612, 618
        }
    }
}
